language: java
jdk: openjdk14

sudo: false

install: true

script: mvn clean package -DskipTests=true

services:
  - postgresql

before_script:
  - psql -c 'create database boot;' -U postgres


after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - david.klarson@mail.co
    on_success: never
    on_failure: always

deploy:
  provider: heroku
  api_key:
    secure: ORYzcZ2c9x7TgWQX+l3iRwGCWzNAKvj4+PtQaqsa2jcQzQduA5EcOBAG3OhVEM65G/pxUY3C0pqrnCjElw8La512UfF+NN8zPOx4b7KeQh6lRzk3U50NmUZb9EmE6s+3QKw0dfHUUHEBJ3bQNBeJX7TqyYN9c0YG/7wtlldicXb6bxARJ47bu3k68b9uUKKGhSHaQ73OU3XKtCBW5RmOmYK28ZgE7mhKP9WGNcOwSwm65Agu5ArchcdbYBYgHqNUfna4fysVjD3kfNzYYOb69nxwQuCzV1LfP5Q9u8o4rc/vT2suL1PYPGaMBcKsG8YHxEiQS6Y4BF1m2DfdOhukgVltZ1arHMOdRXKSv7vjG/FjA5pDrjgRxe+wAnmxE8Bp24imQ0TEF98WPlW0DRBvgH6mR3CyHw2evcCwSo00YiYUlp5IKNa/6EMx5Ur0ZB/c7K6saz3qWZ/87tdV0wZ5Y8egXfIyQqMBKlFmbg1Pen6jyex4Mnne/ILQ6WeTodkmOfuQx7rB30X0yn0CFyervSB+haS9GkWuplFLYiS28FzgSnMc/3WAL6rs3r+F67Gi+cYlbvFvNqE/8IfUfs8Sl81+OJ1Id/0GjnDQemoYqTgz2GigUbB5pjMIZgEthu8RAfK6qskVJ8zSeZ5nkDMB9l/TAk8JXj+nUSmakhrXG+4=
  app: bootforum
