language: java
jdk: openjdk14

sudo: false

install: true

script: mvn clean package -DskipTests=true

services:
  - postgresql

before_script:
  - psql -c 'create database boot;' -U postgres


after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - david.klarson@mail.com
    on_success: never
    on_failure: always

deploy:
  provider: heroku
  api_key:
    secure: RPise5Hxc4GY/+mFCSJrZmEmG0SUvNSLiYZJbcaRzsUjsmQVhrombakFsNhM5eXHTIMBToObH/Yl7dkCdEo/Dv6CTGuiTMlEd6X5EOo0MgWw6kjM+64aik/mtkqBM/74bPl7XNYwO3HFisk/qE8CN1sEX5hQWWRNpRoW1RwXJoinS8BpZHnKpR2BLjkQQZs1tnBZPBHx8A1Gui/M4qV0gTamosvWsZvIksW+ZijwlovfZ2SowLj2DksCTUzq9j7Z9g9FTjzmzRTDFwt5KmRe7W11RRakYYJ9oLO22TlOFNk1Vk7PdFtSq2jEws9YSFdT4obLTeKPLVNFa5S0p1gRMERK+ZM3lMTqFIG5OitCIDFj9EJe71lqUYjox0ccd++FvbfC+ZrgH7s8iU/ATvz6Qh8Sf/DfhZi1qqMRgIXPHIt0tmmHT5oEmY/twXlS4CpGWmEbY4bs4cba8uBphICTrUoT9kGeoXBvhEqTUevicknPS0NUIiWk8MKVsWg9Slvv85ixU8YNIUCKtQ94OIDe0tTCAwGT3Z+AX86oXqYjE0DiaoeS/We+O8NHyKch13p3xDj3rmh0lWH+ip63uSYCeCouLdxqVuFDY3xNp3lhVes+OtANgJ3sTKJ5y/Nj75EdXBsnX+9Ji7hkDD6OSrWhanA0vKLTTiyfdCXNCtZEH78=
  app: bootforum
