language: java
jdk: openjdk14

sudo: false

install: true

script: mvn clean package -DskipTests=true

services:
  - postgresql

before_script:
  - psql -c 'create database boot;' -U postgres


after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - david.klarson@mail.co
    on_success: never
    on_failure: always

deploy:
  provider: heroku
  api_key:
    secure: CCFVfldVMjRtrlForWKMuIbUbBV4OzksIJq3bre2MOMdlaPJ3pJUX6hyJT1JjWsY9zzA72CFBEfKmdFJsT/3jErzY0HV1prKYSK6Cwd8GShlu+QvvCpzCTvQAQZkRAUM+5WCNK5RJqWWRNVIW6FjMMBgM6ky9QlE3E2Um4iL0Sp2CAUo3A0g5ZeLKPORqVMd2OtHM17UoLC+7j3QhNmtVx3jjpADrB8VEdG3JKZjFtOUBimooRnvDEtWNgol8f1wU9MPV7CMQOmMDK3l96DtyC6t8CxhaduS47o7ifIUF10IegqFJZM/P6TGZrSoSsybfXbUdn5kyFEYPm/uzWE287BALNzmeGpN8aq+0YuD1bcYDLgSQF4c/EOxik0mVsQTnLB+Cwf4P2VWdZ4vsIAJ5sUb4lO1eGOideON6WbHf9jLDMpW2jzdGECKWzGDapEmRDpdZFwHzjjxS6Rykjqni9YiGG1bWLkOMujp/x0iZfxCO7lNNHGCZwrioFVOXBT/ZuVnZrhXqlttjKmhKBii/xL5O72MsBsiAXIkO/RPRG8x4N1Zn1huQIHQg+jmtibI/9q0FN2red0CiYNJafoLfklsg8L01bBrO8T2GqiuRoBCrLLcZgf9WDDCIktHnBWldpPXfZQZSKt51qY6vIdbwSQvL11FASd31aQbF1iSp3o=
  app: bootforum
